name: article_idea_generator
description: The mobile version of the Article Idea Generator by Olanetsoft.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_fonts: ^4.0.0
  get_storage: ^2.1.1
  share_plus: ^7.0.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
