name: article_idea_repository
description: A repository that handles article idea related requests.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  article_idea_api:
    path: ../article_idea_api
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
